NumPy算法库是有C语言写的，所以在操作数据内存是，不需要任何类型检查或者其他管理操作。  
NumPy数组使用的内存量也小于其他Python内建序列.  
ndim属性　　shape属性　　dtype属性，dtype是一个特殊的对象，元数据    
astype方法总是生成一个新的数组，不改变原来数组的数据类型

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [6]:
float_arr = arr.astype(np.float64)

In [10]:
float_arr.dtype

dtype('float64')

In [11]:
arr.dtype

dtype('int32')

 区别与Python的内建列表，数组的切片是原数组的视图，这意味着数组并不是被复制了，任何对于视图的修改都会反映到原数组上。  
 如果想要一份数组切片的拷贝而不是一份视图的话，就必须显式地复制这个数组，arr[5:8].copy()  
 使用布尔值索引选择数据时，总是生成数据的拷贝，即使返回的数组并没有任何变化。

In [32]:
a = [1, 2, 3, 4, 5]

In [33]:
a

[1, 2, 3, 4, 5]

In [34]:
x = a[1:3]

In [35]:
x = [500, 600]

In [36]:
x

[500, 600]

In [37]:
a

[1, 2, 3, 4, 5]

神奇索引是NumPy中的术语，用于描述使用整数数组进行数据索引，请牢记神奇索引与切片不同，它总是将数据复制到一个新的数组中。

reshape方法返回视图，不对数组进行修改。  
是不是如果一种方法对对象进行了修改，就没有返回值?　答：不是，列表的pop方法有返回值并且对列表进行了修改  
是不是一种方法没返回值，就一定是对对象进行了修改？　　答：目前学的来看，应该是这样

In [3]:
arr = np.arange(10).reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [1]:
a = [1, 2, 3]
a

[1, 2, 3]

In [2]:
a.append(5)

In [3]:
a.drop()

AttributeError: 'list' object has no attribute 'drop'

transpose方法，swapaxes方法返回数据视图，没有对数据进行复制。

### 通用函数

也称为ufunc，有一元通用函数，二元通用函数等  
通用函数接收一个可选参数out，允许对数组按位置操作（修改）

In [8]:
arr = np.random.randn(10) * 5

In [9]:
arr

array([ -3.02357559,   1.98836338,   8.60439587,   2.3956781 ,
        -3.11143624,  10.05804178,   1.38119425,  -1.18168804,
        -8.39114276,  -4.63667887])

In [10]:
np.sqrt(arr)

C:\Users\Shanks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  1.4100934 ,  2.93332505,  1.54779782,         nan,
        3.17144159,  1.17524221,         nan,         nan,         nan])

In [11]:
arr

array([ -3.02357559,   1.98836338,   8.60439587,   2.3956781 ,
        -3.11143624,  10.05804178,   1.38119425,  -1.18168804,
        -8.39114276,  -4.63667887])

In [12]:
np.sqrt(arr, arr)

C:\Users\Shanks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  1.4100934 ,  2.93332505,  1.54779782,         nan,
        3.17144159,  1.17524221,         nan,         nan,         nan])

In [13]:
arr

array([        nan,  1.4100934 ,  2.93332505,  1.54779782,         nan,
        3.17144159,  1.17524221,         nan,         nan,         nan])

向量化的数组算术与通用函数，只有np.dot是线性代数里的矩阵乘法，使用*和np.multiply都是广播机制

In [26]:
arr = np.random.randn(6, 3)

In [27]:
arr

array([[-0.52863069, -2.10016557,  0.02238172],
       [-0.5832337 , -1.38601963,  0.87267188],
       [ 0.78679351, -0.66507168,  0.95959152],
       [ 2.40980724,  0.0332345 ,  1.45821852],
       [ 0.89702679,  0.83977733, -0.11670801],
       [-1.12244501, -1.61821621, -0.03784536]])

In [28]:
arr.T

array([[-0.52863069, -0.5832337 ,  0.78679351,  2.40980724,  0.89702679,
        -1.12244501],
       [-2.10016557, -1.38601963, -0.66507168,  0.0332345 ,  0.83977733,
        -1.61821621],
       [ 0.02238172,  0.87267188,  0.95959152,  1.45821852, -0.11670801,
        -0.03784536]])

In [29]:
np.dot(arr.T, arr)

array([[  9.11036679,   4.04506147,   3.68601172],
       [  4.04506147,  10.09902038,  -1.88304642],
       [  3.68601172,  -1.88304642,   3.8243273 ]])

In [31]:
arr.T * arr

ValueError: operands could not be broadcast together with shapes (3,6) (6,3) 

In [32]:
np.multiply(arr.T, arr)

ValueError: operands could not be broadcast together with shapes (3,6) (6,3) 

使用数组进行面向数组编程

In [45]:
points = np.arange(-5, 5, 0.01)
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [44]:
np.meshgrid(points, points)

[array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        ..., 
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]]),
 array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
        [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
        [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
        ..., 
        [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
        [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
        [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])]

In [46]:
xs, ys = np.meshgrid(points, points)

In [48]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [50]:
arr = np.random.randn(4, 4)
arr

array([[-0.2168564 ,  0.47834676,  0.61810774,  1.78601065],
       [ 0.40745894,  1.12183471,  1.34094567,  0.6661551 ],
       [ 1.52813891, -2.73471842,  0.10424426,  0.80960298],
       [ 1.2855971 ,  1.388825  ,  0.71304896, -0.50418246]])

In [51]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2, -2,  2,  2],
       [ 2,  2,  2, -2]])

In [53]:
np.where(arr>0, 2, arr)

array([[-0.2168564 ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -2.73471842,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.50418246]])

数学函数，既可以直接调用数组实例的方法，也可以使用顶层的NumPy函数。  
布尔数组，两个非常有用的方法any和all，这些方法也适用于非布尔值数组。  
排序，注意了，学到这里，第一次发现修改数组自身的方法sort（arr.sort(),没返回值，修改原数组，如果x=arr.sort()，x会是None）顶层的np.sort方法返回的是已经排序号的数组拷贝，而不是对原数组按位置排序。  

线性代数，注意矩阵乘法结果，和x那个乘法和线代的直觉不一样，先后顺序遵从线代

In [73]:
arr = np.random.randn(5, 3)

In [74]:
x = np.ones(3)

In [75]:
y = np.ones((3,1))

In [76]:
arr.dot(x)

array([-1.17507394,  1.05241327, -0.66258987,  0.11862498, -2.03054316])

In [78]:
np.dot(arr, y)

array([[-1.17507394],
       [ 1.05241327],
       [-0.66258987],
       [ 0.11862498],
       [-2.03054316]])

__随机漫步__

In [3]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws>0, 1, -1)
walks = steps.cumsum(1)

In [6]:
walks

array([[  1,   0,  -1, ..., -60, -59, -60],
       [ -1,  -2,  -3, ...,  32,  33,  32],
       [  1,   0,   1, ...,  22,  23,  24],
       ..., 
       [  1,   2,   3, ...,  20,  19,  18],
       [ -1,   0,  -1, ...,  52,  51,  52],
       [  1,   2,   1, ..., -34, -35, -34]], dtype=int32)

In [7]:
walks.shape

(5000, 1000)

In [14]:
hists30 = (np.abs(walks) >= 30).any(1)

In [15]:
hists30

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [16]:
hists30.shape

(5000,)

In [18]:
hists30.sum()

3360

In [19]:
crossing_times = (np.abs(walks[hists30]) >= 30).argmax(1)

In [21]:
crossing_times.shape

(3360,)

本章完